# Copyright (C) 2012 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/lge/p920/setup-makefiles.sh

VENDOR_FOLDER := vendor/lge/p920/proprietary

# Bluetooth & Fm-Radio
PRODUCT_COPY_FILES += \
    $(VENDOR_FOLDER)/etc/firmware/fm_rx_init_1273.2.bts:system/etc/firmware/fm_rx_init_1273.2.bts \
    $(VENDOR_FOLDER)/etc/firmware/TIInit_7.2.31.bts:system/etc/firmware/TIInit_7.2.31.bts \
    $(VENDOR_FOLDER)/etc/firmware/fmc_init_1273.2.bts:system/etc/firmware/fmc_init_1273.2.bts \
    $(VENDOR_FOLDER)/etc/firmware/fm_tx_init_1273.2.bts:system/etc/firmware/fm_tx_init_1273.2.bts 

# Gps
PRODUCT_COPY_FILES += \
    $(VENDOR_FOLDER)/etc/cert/lge.cer:system/etc/cert/lge.cer \
    $(VENDOR_FOLDER)/lib/hw/gps.omap4.so:system/lib/hw/gps.omap4.so \
    $(VENDOR_FOLDER)/bin/glgps:system/bin/glgps 

# Ril
PRODUCT_COPY_FILES += \
    $(VENDOR_FOLDER)/lib/libril.so:system/lib/libril.so \
    $(VENDOR_FOLDER)/lib/lge-ril.so:system/lib/lge-ril.so \
    $(VENDOR_FOLDER)/lib/libini.so:system/lib/libini.so \
    $(VENDOR_FOLDER)/bin/rild:system/bin/rild

# Audio
PRODUCT_COPY_FILES += \
    $(VENDOR_FOLDER)/lib/libmmclient.so:system/lib/libmmclient.so \
    $(VENDOR_FOLDER)/lib/libacousticengine.so:system/lib/libacousticengine.so \
    $(VENDOR_FOLDER)/lib/libaudiomodemgeneric.so:system/lib/libaudiomodemgeneric.so \
    $(VENDOR_FOLDER)/lib/libasound.so:system/lib/libasound.so
 
# Hal
PRODUCT_COPY_FILES += \
    $(VENDOR_FOLDER)/lib/hw/sensors.omap4.so:system/lib/hw/sensors.omap4.so 

# Sensors
PRODUCT_COPY_FILES += \
    $(VENDOR_FOLDER)/lib/libmpl.so:system/lib/libmpl.so \
    $(VENDOR_FOLDER)/lib/libmllite.so:system/lib/libmllite.so \
    $(VENDOR_FOLDER)/lib/libmlplatform.so:system/lib/libmlplatform.so

# Hdmi
PRODUCT_COPY_FILES += \
    $(VENDOR_FOLDER)/lib/liblgehdmi.so:system/lib/liblgehdmi.so \
    $(VENDOR_FOLDER)/lib/libhdcp.so:system/lib/libhdcp.so

# Sgx-Pvr
PRODUCT_COPY_FILES += \
    $(VENDOR_FOLDER)/etc/powervr.ini:/system/etc/powervr.ini \
    $(VENDOR_FOLDER)/vendor/bin/pvrsrvinit:system/vendor/bin/pvrsrvinit \
    $(VENDOR_FOLDER)/vendor/bin/pvrsrvctl_SGX540_120:system/vendor/bin/pvrsrvctl_SGX540_120 \
    $(VENDOR_FOLDER)/vendor/firmware/ducati-m3.512MB.bin:system/etc/firmware/ducati-m3.512MB.bin \
    $(VENDOR_FOLDER)/vendor/lib/hw/gralloc.omap4430.so:system/vendor/lib/hw/gralloc.omap4430.so \
    $(VENDOR_FOLDER)/vendor/lib/libPVRScopeServices_SGX540_120.so:system/vendor/lib/libPVRScopeServices_SGX540_120.so \
    $(VENDOR_FOLDER)/vendor/lib/libIMGegl_SGX540_120.so:system/vendor/lib/libIMGegl_SGX540_120.so \
    $(VENDOR_FOLDER)/vendor/lib/libsrv_init_SGX540_120.so:system/vendor/lib/libsrv_init_SGX540_120.so \
    $(VENDOR_FOLDER)/vendor/lib/libpvrANDROID_WSEGL_SGX540_120.so:system/vendor/lib/libpvrANDROID_WSEGL_SGX540_120.so \
    $(VENDOR_FOLDER)/vendor/lib/libglslcompiler_SGX540_120.so:system/vendor/lib/libglslcompiler_SGX540_120.so \
    $(VENDOR_FOLDER)/vendor/lib/libpvr2d_SGX540_120.so:system/vendor/lib/libpvr2d_SGX540_120.so \
    $(VENDOR_FOLDER)/vendor/lib/libsrv_um_SGX540_120.so:system/vendor/lib/libsrv_um_SGX540_120.so \
    $(VENDOR_FOLDER)/vendor/lib/libusc_SGX540_120.so:system/vendor/lib/libusc_SGX540_120.so \
    $(VENDOR_FOLDER)/vendor/lib/egl/libGLESv2_POWERVR_SGX540_120.so:system/vendor/lib/egl/libGLESv2_POWERVR_SGX540_120.so \
    $(VENDOR_FOLDER)/vendor/lib/egl/libEGL_POWERVR_SGX540_120.so:system/vendor/lib/egl/libEGL_POWERVR_SGX540_120.so \
    $(VENDOR_FOLDER)/vendor/lib/egl/libGLESv1_CM_POWERVR_SGX540_120.so:system/vendor/lib/egl/libGLESv1_CM_POWERVR_SGX540_120.so 

# Widevine
PRODUCT_COPY_FILES += \
    $(VENDOR_FOLDER)/vendor/lib/libwvm.so:system/vendor/lib/libwvm.so \
    $(VENDOR_FOLDER)/vendor/lib/libwvdrm_L3.so:system/vendor/lib/libwvdrm_L3.so \
    $(VENDOR_FOLDER)/vendor/lib/libWVStreamControlAPI_L3.so:system/vendor/lib/libWVStreamControlAPI_L3.so \
    $(VENDOR_FOLDER)/vendor/lib/drm/libdrmwvmplugin.so:system/vendor/lib/drm/libdrmwvmplugin.so
  

# Wifi & Softap
PRODUCT_COPY_FILES += \
    $(VENDOR_FOLDER)/etc/wifi/firmware.bin:system/etc/wifi/firmware.bin \
    $(VENDOR_FOLDER)/etc/wifi/softap/firmware_ap.bin:system/etc/wifi/softap/firmware_ap.bin \
    $(VENDOR_FOLDER)/etc/firmware/ti-connectivity/wl127x-fw-4-sr.bin:system/etc/firmware/ti-connectivity/wl127x-fw-4-sr.bin \
    $(VENDOR_FOLDER)/etc/firmware/ti-connectivity/wl127x-fw-4-mr.bin:system/etc/firmware/ti-connectivity/wl127x-fw-4-mr.bin \
    $(VENDOR_FOLDER)/etc/firmware/ti-connectivity/wl127x-fw-4-plt.bin:system/etc/firmware/ti-connectivity/wl127x-fw-4-plt.bin \
    $(VENDOR_FOLDER)/etc/firmware/ti-connectivity/wl1271-nvs.bin:system/etc/firmware/ti-connectivity/wl1271-nvs.bin


# Other
PRODUCT_COPY_FILES += \
    $(VENDOR_FOLDER)/vendor/lib/libsmapi.so:system/vendor/lib/libsmapi.so \
    $(VENDOR_FOLDER)/vendor/lib/liblvvetx.so:system/vendor/lib/liblvvetx.so \
    $(VENDOR_FOLDER)/vendor/lib/liblvverx.so:system/vendor/lib/liblvverx.so
